# Generated by Django 5.0 on 2023-12-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planwood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
