# Generated by Django 5.0 on 2023-12-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planwood', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [-1, 'date_task_created']},
        ),
    ]
