# Generated by Django 5.0 on 2023-12-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planwood', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date_task_created']},
        ),
    ]
