# Generated by Django 5.0 on 2023-12-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planwood', '0008_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name']},
        ),
    ]
