# Generated by Django 5.0 on 2023-12-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0003_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
