# Generated by Django 5.0 on 2023-12-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wood', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_task_created']},
        ),
    ]
